import React from "react"
import './index.css'

export default function Background() {
    return (
            <section style={{paddingTop: "50px"}}>
                {/* <h4 className="subhead" style={{paddingTop: "50px"}}>Background</h4> */}
                <p>
                In the first year of the COVID-19 pandemic, news and opinion headlines in New York City’s leading newspapers painted, for some audiences, an alarming effect on city real estate – rich neighborhoods "<a href='https://www.nytimes.com/interactive/2020/05/15/upshot/who-left-new-york-coronavirus.html' target='_blank'>emptied out</a>", the pandemic has "<a href='https://nypost.com/2020/07/10/covid-19-has-broken-nycs-housing-market/' target='_blank'>broken</a>" the housing market, data show a "<a href='https://nypost.com/2020/11/14/new-stats-reveal-massive-nyc-exodus-amid-coronavirus-crime/' target='_blank'>massive NYC exodus</a>." Then, just a year later, still amid the pandemic, the housing market has "<a href='https://www.nytimes.com/2021/10/05/realestate/new-york-real-estate-sales.html' target='_blank'>surged</a>", "<a href='https://www.nytimes.com/2021/12/29/nyregion/chelsea-nyc-coronavirus.html' target='_blank'>bounce[d] back</a>", "made a <a href='https://www.nytimes.com/2021/12/31/realestate/in-2021-new-yorks-housing-market-made-a-stunning-comeback.html' target='_blank'>stunning comeback</a>", and "<a href='https://www.wsj.com/articles/manhattan-luxury-home-sales-skyrocketed-in-2021-11641301201' target='_blank'>skyrocketed</a>." These headlines would suggest that real estate has not just recovered, but could be on the verge of a boom, to follow the cycle described in the report "Corporate Windfalls or Social Housing Conversions?" released in November 2020 by the nonprofit Community Service Society of New York. The market undulates from a high at the "euphoria" stage to a low at the "crisis" stage but despite these contrasting names, for speculators and investors, each stage whether high or low strike to make money while for many tenants living in buildings of interest, the cycle appears more as a line, of ongoing rent increases and lack of maintenance (Hornbach et al. 4). The pandemic certainly initiated extraordinary circumstances that left many unable to pay their rent and debts mounted for both tenants and landlords, with foreclosures seemingly inevitable.
                </p>
                <p>
                But at the root of these tensions is the reality that tenant fears of displacement, a lack of building maintenance, changing ownership, stretch back to years before the pandemic. A tendency of some city landlords and and investors to take questionable approaches in the pursuit of profit stem back a quarter of a century (3). The practice of perceiving housing as an investment vehicle for making profits is described as real estate speculation. In pursuit of profit, landlords can end up engaging in predatory practices that drive out long-time tenants in favor of higher-income occupants (Klein et al. 19). The headlines and the real estate cycle, obscure the reality for many renters, in a city where <a href='https://furmancenter.org/stateofthecity/view/state-of-renters-and-their-homes' target='_blank'>two-thirds rent</a> their home – that much of the housing crises of the past nearly two years did not emerge during the onset of the pandemic; rather the pandemic exacerbated a housing market debacle some 25 years in the making, following lending deregulations, cuts in urban funding, and the increasing growth and influence of the financial service industry (Hornbach et al. 2020, 8; Klein et al., n.d., 20).
                </p>
                <p>For my capstone project, with the precarious NYC housing market, and speculation, as the backdrop, I will explore a dataset of Tax Commission Income and Expense (TCIE) filings and see how data visualizations can help navigate the contents and potentially find stories of displacement and distress.</p>
            </section>
    )
}